name: 'Pull request labeled'
on:
  pull_request:
    types: [labeled]

jobs:
  pull_request_labeled_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Shuttlerock/actions/actions/pull-request-labeled-action@master
        with:
          organization-name: ${{ secrets.ORGANIZATION_NAME }}
          repo-token:        ${{ secrets.GITHUB_TOKEN }}
          slack-token:       ${{ secrets.SLACK_TOKEN }}
          write-token:       ${{ secrets.ACTIONS_WRITE_TOKEN }}
